'use client';

import { useState } from 'react';
import Link from 'next/link';
import { Search, Compass, CheckSquare, FolderKanban, Clock, CalendarDays, Inbox, FileText, BookOpen, Columns3, ClipboardCheck, LockKeyhole, Radar, FileBarChart2, UsersRound, RefreshCw, Settings, Archive, ListChecks } from 'lucide-react';

const GUIDE_SECTIONS = [
  { id: 'start', title: 'Getting Started', icon: Compass, href: '/', intro: 'OmniTool keeps your work, promises, meetings, and notes in one place. Start small; you do not need to fill every section.', steps: ['Create a project for work that has a shared goal or delivery date.', 'Add tasks with a clear next action, an owner, and a due date when needed.', 'Use Quick Capture for new requests you want to remember. You can organise them later in Inbox.', 'Open Today each morning and choose a few priorities.'], tip: 'Collapse the left navigation when you need more space. Hover over an icon to see its name.' },
  { id: 'daily', title: 'A Simple Daily Routine', icon: ListChecks, href: '/review', intro: 'Use a short morning check and an end-of-day review instead of constantly reorganising your work.', steps: ['Morning: check Today for overdue work, follow-ups, and meetings.', 'Choose up to three existing tasks or follow-ups in Focus Plan and write the next action.', 'During the day: capture new requests, update progress, and record replies.', 'Evening: open Day Review, reschedule unfinished work, and prepare tomorrow.'], tip: 'A task deadline is not the same as a plan for today. Focus Plan lets you choose priorities without copying tasks.' },
  { id: 'today', title: 'Today & Focus Plan', icon: Compass, href: '/', intro: 'Your starting point for important work, deadlines, waiting items, and meetings.', steps: ['Open a highlighted item to see its context and take action.', 'Add existing work to Focus Plan rather than creating a second copy.', 'Reorder or remove focus items as priorities change.', 'Complete a focus item when the underlying work is actually finished.'], tip: 'Completing a focus item completes its task or resolves its follow-up.' },
  { id: 'my-work', title: 'My Work', icon: CheckSquare, href: '/my-work', intro: 'See tasks and follow-ups across projects instead of opening each project separately.', steps: ['Choose Assigned to me, Following, or Workspace.', 'Use Today, This Week, Overdue, Waiting, or All to choose a time/work view.', 'Filter by project, client, person, or priority. Save a useful combination as a named view.', 'Select several items to reschedule, complete, follow, archive, or move them to Trash.'], tip: 'If Assigned to me is empty, check the owner or linked directory person on your work. Workspace shows shared work from everyone.' },
  { id: 'planner', title: 'Day Planner & Unblock Radar', icon: Radar, href: '/planning', intro: 'Check whether work fits around your meetings and discover which task could unlock other work.', steps: ['Set your working hours and days off in My Preferences.', 'Add realistic time estimates in Task Detail.', 'Choose a date to see available time and suggested work that fits.', 'Use Unblock Radar to preview the effect of completing a blocking task.'], tip: 'A preview changes nothing. Add work to Focus only after deciding it is a priority.' },
  { id: 'reports', title: 'Work Reports', icon: FileBarChart2, href: '/reports', intro: 'A consolidated view of projects and tasks, including older and completed work.', steps: ['Choose Projects & Tasks, Projects, or Tasks.', 'Filter by status, priority, owner, project, client, or a date range.', 'Select Include archived when you need archived history.', 'Download CSV or Excel to extract the matching records, not just the page you can see.'], tip: 'Drag a column edge to adjust its width. The Type column shows whether a row is a task or a project. Reset column widths restores the original layout.' },
  { id: 'projects', title: 'Projects & Clients', icon: FolderKanban, href: '/projects', intro: 'Group related work under a client and project, with a shared objective and delivery date.', steps: ['Create a client when you need to distinguish work for different organisations.', 'Create a project, then add tasks, deliverables, follow-ups, notes, or a QC checklist.', 'Use the project tabs to see work and its supporting context.', 'Choose Complete project when delivery is finished. Reopen it if work resumes.'], tip: 'Project completion leaves open tasks and follow-ups unchanged and pauses its cadence. Archive hides a project; it does not mean the project is finished.' },
  { id: 'tasks', title: 'Task Details & Dependencies', icon: CheckSquare, href: '/my-work', intro: 'Use a task for an action that someone needs to complete.', steps: ['Give the task a clear title, owner, priority, and due date if there is a deadline.', 'Use subtasks to break the work into smaller steps.', 'Add a dependency when another task must finish first.', 'Update status to In Progress, Waiting, or Blocked as appropriate, then mark Done when finished.'], tip: 'Open the linked blocker to understand what you are waiting for. Archiving an unfinished prerequisite does not complete it.' },
  { id: 'people', title: 'People & Teams', icon: UsersRound, href: '/teams', intro: 'Keep a reusable directory of the people and teams involved in your work.', steps: ['Add a person so assignments and follow-ups can refer to the same contact.', 'Group people into teams and attach them to projects.', 'Choose a directory person when assigning a task or recording who you are waiting on.'], tip: 'A directory contact is not automatically an app account. Account invitations are managed separately in Settings.' },
  { id: 'followups', title: 'Follow-ups', icon: Clock, href: '/followups', intro: 'Track promises, approvals, responses, and work you are waiting on.', steps: ['Record what is needed, who you are waiting on, and the expected date.', 'Add context so you do not need to reconstruct the conversation later.', 'Use Record nudge after you have actually followed up with the person.', 'Resolve the item when the response or action arrives, or escalate it when it needs attention.'], tip: 'Record nudge records your action; it does not send a message for you.' },
  { id: 'cadence', title: 'Cadence', icon: RefreshCw, href: '/cadence', intro: 'Use recurring rules for work that returns regularly under a project.', steps: ['Choose the project, recurring action, first due date, and frequency.', 'Let each due occurrence appear as a task rather than copying the whole project.', 'Pause a rule when the obligation stops and resume it explicitly when needed.'], tip: 'Completing a project pauses its cadence. Reopening the project does not automatically resume old rules.' },
  { id: 'calendar', title: 'Calendar', icon: CalendarDays, href: '/calendar', intro: 'See meetings alongside your work, including local events and connected calendar overlays.', steps: ['Use Upcoming for ongoing/future events, Past for available history, or Date range.', 'Create and edit local events in OmniTool.', 'Use Outcome on a meeting to create a note, task, or follow-up with its origin retained.', 'Check overlap or stale-calendar indicators before relying on the agenda.'], tip: 'Connected calendar events are read-only here. Change an imported meeting in its original calendar.' },
  { id: 'inbox', title: 'Inbox & Quick Capture', icon: Inbox, href: '/inbox', intro: 'A place for unorganised requests and thoughts you do not want to forget.', steps: ['Use Quick Capture or Ctrl + Space to enter a thought without choosing a category.', 'Open Inbox when you have time to organise it.', 'Convert a capture into a task, follow-up, or note and choose its project if useful.', 'If an optional AI suggestion is available, review it before accepting.'], tip: 'A capture is not yet a scheduled commitment. Processing Inbox gives it an owner, purpose, and dates when needed.' },
  { id: 'notes', title: 'Notes', icon: FileText, href: '/notes', intro: 'Short, lightweight notes linked to the work or conversation they support.', steps: ['Create a note and add useful context.', 'Link it to a project, task, follow-up, or other related item.', 'Keep it Private for personal working notes, or explicitly share it with the workspace.', 'Save edits and reopen a note if another tab has changed it.'], tip: 'Private ordinary notes are not the same as encrypted Secure Vault notes.' },
  { id: 'notebooks', title: 'Notebooks', icon: BookOpen, href: '/notebooks', intro: 'Use notebooks and pages for longer meeting records, plans, and organised working documents.', steps: ['Choose a notebook and page, or create them when you need a new document.', 'Use the toolbar for headings, fonts, colour, lists, checklists, code, and tables.', 'Save explicitly. Use saved revisions to restore an earlier version when needed.', 'Export as DOCX, or use Print to save a PDF.'], tip: 'Hide the notebook/pages rails or choose Focus editor to gain space. Reading mode hides editing controls; it does not discard an unsaved draft.' },
  { id: 'files', title: 'File Views', icon: Columns3, href: '/file-views', intro: 'Bring an existing Excel or CSV tracker into a read-only view without rebuilding every row by hand.', steps: ['Import an XLSX or CSV file and choose Private or Shared.', 'Select a sheet, search/filter/sort rows, and choose which columns to display.', 'Drag column edges to resize them and use the table scrollbar for additional columns.', 'Map a unique row ID and title before creating tasks or follow-ups from selected rows.', 'Refresh with a newer copy when the source tracker changes.'], tip: 'Refreshing does not overwrite linked work or create duplicate conversions. The source file stays separate; OmniTool is not a spreadsheet editor.' },
  { id: 'qc', title: 'QC Checklists', icon: ClipboardCheck, href: '/qc', intro: 'Track the checks that must be satisfied before work is ready to deliver.', steps: ['Create or reuse a QC template.', 'Attach a checklist to the project, task, or deliverable.', 'Mark checks as complete and keep notes or reviewer details where needed.'], tip: 'QC checks are checklist items, not extra tasks unless you choose to create work separately.' },
  { id: 'vault', title: 'Secure Vault', icon: LockKeyhole, href: '/vault', intro: 'A separate place for sensitive notes protected by its own password. Available to workspace Admins.', steps: ['Open Secure Vault and choose a strong master password the first time.', 'Unlock with that password whenever you return to the Vault.', 'Create, edit, and save secure notes inside the Vault, not ordinary Notes.', 'Use Lock Vault when finished. Leaving the Vault also locks it.', 'To change the password, unlock first and use Change Password.'], tip: 'Keep the Vault password somewhere safe outside OmniTool. Forgot vault password resets to an empty Vault after confirmation; it cannot recover old notes and does not remove backup copies.' },
  { id: 'review', title: 'Day & Week Review', icon: ListChecks, href: '/review', intro: 'Close the day or week with a short review of completed work, unfinished commitments, and upcoming priorities.', steps: ['Check what was completed and what still needs attention.', 'Reschedule unfinished work deliberately instead of allowing dates to drift.', 'Review pending follow-ups and new captures.', 'Prepare tomorrow or next week and save any personal review notes.'], tip: 'Optional AI drafts are suggestions; applying and saving them remains your decision.' },
  { id: 'search', title: 'Search', icon: Search, href: '/search', intro: 'Find an item without remembering which screen or project contains it.', steps: ['Search by a title or phrase, or use relationship filters.', 'Choose the item type when you need to narrow the results.', 'Open a matching result to go directly to the record.', 'Use the sidebar shortcut for quick search from another page.'], tip: 'Private notes and notebook pages are visible only to their owner unless shared.' },
  { id: 'archive', title: 'Archive & Trash', icon: Archive, href: '/trash', intro: 'Keep active views clear without confusing finished work with deleted work.', steps: ['Complete work when finished; cancel it when it is no longer required.', 'Archive records you want hidden from active lists but retained.', 'Move a record to Trash if you want to remove it while keeping a restore option.', 'Use Undo or Restore after an accidental deletion.'], tip: 'Delete permanently cannot be undone and requires confirmation. A backup may retain its own separate copy.' },
  { id: 'preferences', title: 'My Preferences', icon: Settings, href: '/preferences', intro: 'Personal settings for alerts, working time, reminders, and your account password.', steps: ['Choose alert categories, quiet hours, and meeting lead time.', 'Set your timezone, working hours, days off, and daily work budget.', 'Create a personal reminder for a task, follow-up, or meeting.', 'Use Account to change your sign-in password.'], tip: 'Browser alerts require an open app and browser notification permission. Save preferences after changing them.' },
  { id: 'settings', title: 'Settings & Recovery', icon: Settings, href: '/settings', intro: 'Workspace-wide controls for Admins, separate from personal Preferences.', steps: ['Workspace Access: invite accounts and choose their roles.', 'Security: manage the screen-lock PIN and check security status.', 'Integrations: connect calendars or an optional AI provider.', 'Data & Recovery: export records, create a verified backup, or prepare a restore.'], tip: 'A record export and a full recovery backup serve different purposes. Keep backups safe; restoring does not silently replace the running workspace.' },
];

export default function GuideView() {
  const [query, setQuery] = useState('');
  const sections = GUIDE_SECTIONS.filter((section) => [section.title, section.intro, section.tip, ...section.steps].join(' ').toLowerCase().includes(query.trim().toLowerCase()));
  return <div className="guide-view"><div className="page-header"><h1>OmniTool Guide</h1><p>Find the right place for your work and learn the everyday actions.</p></div>
    <label className="guide-search"><Search size={18} /><input className="form-input" type="search" aria-label="Search the guide" placeholder="Search the guide" value={query} onChange={(event) => setQuery(event.target.value)} /></label>
    <div className="guide-layout"><nav className="guide-navigation" aria-label="Guide topics">{sections.map(({ id, title }) => <a href={`#${id}`} key={id}>{title}</a>)}</nav>
      <div className="guide-content">{sections.map(({ id, title, intro, steps, tip, icon: Icon, href }) => <section id={id} className="guide-section" key={id}><div className="guide-heading"><Icon size={20} /><h2>{title}</h2><Link href={href}>Open section</Link></div><p>{intro}</p><ol>{steps.map((step) => <li key={step}>{step}</li>)}</ol><p className="guide-tip">{tip}</p></section>)}{!sections.length && <p className="work-muted">No matching topics. Try a section name or an action such as export, complete, or password.</p>}</div>
    </div>
  </div>;
}